version: '3.8'

services:
  app:
    build:
      context: .
    container_name: server-app-1
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_NAME: new_portfolio
      DB_USER: root
      DB_PASSWORD: portfolio
      DB_HOST: mysql
      DB_PORT: 3306

  mysql:
    image: mysql:8.0
    container_name: server-mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: portfolio
      MYSQL_DATABASE: new_portfolio
      MYSQL_USER: root
      MYSQL_PASSWORD: portfolio
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
